[package]
name = "rfb-client"
version = "0.1.0"
edition = "2021"
default-run = "gui"

[dependencies]
anyhow = "1.0.66"
clap = "3"
clap_derive = "3"
klask = { git = "https://github.com/MichalGniadek/klask" }
rfb-proto = { path = "../proto", features = ["sensor", "actuator"] }
serialport = "4"
